disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - explicit_init
  - first_where
  - modifier_order
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - sorted_imports
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - pattern_matching_keywords
  - fatal_error_message
  - closure_end_indentation
  - closure_parameter_position
  - conditional_returns_on_newline
  - explicit_failure_calls
  - force_unwrapping
  - implicitly_unwrapped_optional
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - prefixed_toplevel_constant
  - redundant_nil_coalescing
  - redundant_void_return
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument

excluded:
  - Carthage
  - Pods
  - Generated
  - fastlane
  - build

force_cast: warning
force_try:
  severity: warning
function_body_length:
  warning: 60
  error: 100
type_body_length:
  warning: 300
  error: 500
file_length:
  warning: 500
  error: 1000
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k
    - vc
reporter: "xcode" 