import Foundation
import PDFKit

/// Service responsible for payslip sharing functionality
/// Part of the unified architecture for consistent sharing across the app
@MainActor
class PayslipSharingService: @preconcurrency PayslipSharingServiceProtocol {
    // Uses the shared CurrencyFormatter from Shared/Utilities

    /// Gets a formatted string representation of the payslip for sharing
    ///
    /// - Parameter payslipData: The payslip data to format
    /// - Returns: A formatted string with payslip details
    func getShareText(for payslipData: PayslipData) -> String {
        let creditsStr = CurrencyFormatter.format(payslipData.totalCredits)
        let debitsStr = CurrencyFormatter.format(payslipData.totalDebits)
        let dsopStr = CurrencyFormatter.format(payslipData.dsop)
        let taxStr = CurrencyFormatter.format(payslipData.incomeTax)
        let netStr = CurrencyFormatter.format(payslipData.netRemittance)

        var description = """
        PAYSLIP DETAILS
        ---------------

        PERSONAL DETAILS:
        Name: \(payslipData.name)
        Month: \(payslipData.month)
        Year: \(payslipData.year)

        FINANCIAL DETAILS:
        Credits: \(creditsStr)
        Debits: \(debitsStr)
        DSOP: \(dsopStr)
        Tax: \(taxStr)
        Net Amount: \(netStr)
        """

        // Add earnings breakdown if available
        if !payslipData.allEarnings.isEmpty {
            description += "\n\nEARNINGS BREAKDOWN:"
            for (key, value) in payslipData.allEarnings.sorted(by: { $0.key < $1.key }) {
                if value > 0 {
                    let valueStr = CurrencyFormatter.format(value)
                    description += "\n\(key): \(valueStr)"
                }
            }
        }

        // Add deductions breakdown if available
        if !payslipData.allDeductions.isEmpty {
            description += "\n\nDEDUCTIONS BREAKDOWN:"
            for (key, value) in payslipData.allDeductions.sorted(by: { $0.key < $1.key }) {
                if value > 0 {
                    let valueStr = CurrencyFormatter.format(value)
                    description += "\n\(key): \(valueStr)"
                }
            }
        }

        description += "\n\nGenerated by PayslipMax"

        return description
    }

    /// Gets both text and PDF data for sharing if available
    ///
    /// - Parameters:
    ///   - payslipData: The payslip data
    ///   - payslip: The payslip item (if available)
    /// - Returns: An array of items to share
    func getShareItems(for payslipData: PayslipData, payslip: AnyPayslip?) async -> [Any] {
        let shareText = getShareText(for: payslipData)

        // Check if we have PDF data to share
        guard let payslipItem = payslip as? PayslipItem,
              let pdfData = payslipItem.pdfData,
              !pdfData.isEmpty else {
            // Return just text if no PDF data
            return [shareText]
        }

        // Create temporary URL for the PDF
        let tempFileName = "\(payslipData.month)_\(payslipData.year)_Payslip.pdf"
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent(tempFileName)

        do {
            // Write PDF data to temp file for sharing
            try pdfData.write(to: tempURL)
            // Return both text and PDF URL
            return [shareText, tempURL]
        } catch {
            print("Error preparing PDF for sharing: \(error)")
            // Return just text if we couldn't prepare the PDF
            return [shareText]
        }
    }

    /// Get the URL for sharing the PDF
    ///
    /// - Parameter payslip: The payslip to get PDF for
    /// - Returns: URL to the PDF file
    /// - Throws: Error if PDF cannot be prepared
    func getPDFURL(for payslip: AnyPayslip) async throws -> URL? {
        guard let payslipItem = payslip as? PayslipItem else {
            throw AppError.message("Cannot share PDF: Invalid payslip type")
        }

        // Check if PDF is already stored
        if let url = PDFManager.shared.getPDFURL(for: payslipItem.id.uuidString) {
            print("PDF found at: \(url.path)")
            return url
        }

        // If not stored, get the PDF data and save it
        guard let pdfData = payslipItem.pdfData else {
            throw AppError.message("Cannot share PDF: No PDF data available")
        }

        do {
            print("Saving PDF data of size: \(pdfData.count) bytes")
            let url = try PDFManager.shared.savePDF(
                data: pdfData,
                identifier: payslipItem.id.uuidString
            )
            print("PDF saved successfully at: \(url.path)")
            return url
        } catch {
            print("Error saving PDF: \(error.localizedDescription)")
            throw AppError.message("Failed to save PDF: \(error.localizedDescription)")
        }
    }
}
