import Foundation
@testable import PayslipMax

/// Mock implementation of PayslipFormatterService for testing
class MockPayslipFormatterService: PayslipFormatterService {
    
    // MARK: - Mock State
    var mockFormattedCurrency = "₹1,234"
    var mockFormattedYear = "2025"
    var mockShareText = "Mock Share Text"
    
    // Track method calls
    var formatCurrencyCallCount = 0
    var formatYearCallCount = 0
    var getShareTextCallCount = 0
    
    override init() {
        super.init()
    }
    
    override func formatCurrency(_ value: Double?) -> String {
        formatCurrencyCallCount += 1
        
        guard let value = value else {
            return "₹0"
        }
        
        // Simple currency formatting for testing
        let formatter = NumberFormatter()
        formatter.numberStyle = .currency
        formatter.currencySymbol = "₹"
        formatter.minimumFractionDigits = 0
        formatter.maximumFractionDigits = 0
        formatter.usesGroupingSeparator = true
        
        return formatter.string(from: NSNumber(value: value)) ?? "₹\(Int(value))"
    }
    
    override func formatYear(_ year: Int) -> String {
        formatYearCallCount += 1
        return String(year)
    }
    
    override func getShareText(for payslipData: Models.PayslipData) -> String {
        getShareTextCallCount += 1
        
        return """
        Payslip - \(payslipData.month) \(payslipData.year)
        
        Name: \(payslipData.name)
        Net Amount: \(formatCurrency(payslipData.netRemittance))
        
        Generated by PayslipMax
        """
    }
    
    // MARK: - Test Helper Methods
    
    func reset() {
        formatCurrencyCallCount = 0
        formatYearCallCount = 0
        getShareTextCallCount = 0
        mockFormattedCurrency = "₹1,234"
        mockFormattedYear = "2025"
        mockShareText = "Mock Share Text"
    }
    
    func setMockFormattedCurrency(_ value: String) {
        mockFormattedCurrency = value
    }
    
    func setMockFormattedYear(_ value: String) {
        mockFormattedYear = value
    }
    
    func setMockShareText(_ value: String) {
        mockShareText = value
    }
}