name: CI

on:
  push:
    branches: [ main, development, 'feature/*' ]
  pull_request:
    branches: [ main, development ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Build
      run: |
        xcodebuild clean build -scheme "PayslipMax" -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest"

    - name: Run Tests
      run: |
        xcodebuild test -scheme "PayslipMax" -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest" -enableCodeCoverage YES

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 