name: SwiftLint

on:
  push:
    branches: [ main, development, 'feature/*' ]
  pull_request:
    branches: [ main, development ]

jobs:
  lint:
    name: SwiftLint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict 