name: UI Tests

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  ui-tests:
    name: UI Tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Run UI Tests
      run: |
        xcodebuild test -scheme "PayslipMax" -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest" -testPlan "UITests" 